name: Auto Job Apply
on:
  schedule:
    - cron: '13 10 * * *'
  workflow_dispatch:
jobs:
  job-search:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python scripts/main.py
        env:
          ADZUNA_API_KEY: ${{ secrets.ADZUNA_API_KEY }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          WHATSAPP_NUMBER: ${{ secrets.WHATSAPP_NUMBER }}
